version: '3.8'

services:
  postgres:
    container_name: bitirme-postgre
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre5432
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: bitirme-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Geliştirme ortamı için güvenliği kapatıyoruz. canlıya alırken bu ayar kesinlikle kapatılmalı
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es-data:/usr/share/elasticsearch/data

  redis:
    image: redis:7-alpine
    container_name: bitirme-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.0
    container_name: bitirme-kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    depends_on:
      - elasticsearch


volumes:
  postgres-data:
  es-data:
  redis-data:
